# frozen_string_literal: true

module RouteSchemer
  # Builds an OpenAPI-style document out of the request/response schemas already defined on
  # `*RouteSchemer` classes, so schemas written once for validation can also be surfaced to
  # tools like Swagger UI without hand-maintaining a separate spec.
  #
  # @example
  #   RouteSchemer::SwaggerGenerator.generate([FooRouteSchemer])
  #   # => { "Foo" => { "demo" => { request: {...}, response: {...} } } }
  module SwaggerGenerator
    module_function

    # @param route_schemer_classes [Array<Class>] classes exposing `<action>_request_schema` /
    #   `<action>_response_schema` class methods, as generated by `rails g route_schemer`
    # @return [Hash] a document keyed by controller name, then action name, holding the
    #   request/response schemas defined for that action
    def generate(route_schemer_classes)
      route_schemer_classes.each_with_object({}) do |klass, doc|
        controller_name = klass.name.to_s.delete_suffix("RouteSchemer")
        next if controller_name.empty?

        actions = schema_actions(klass)
        next if actions.empty?

        doc[controller_name] = actions.to_h { |action| [action, schemas_for(klass, action)] }
      end
    end

    # Discovers every `*RouteSchemer` class currently loaded (excluding the shared base class)
    # and builds their combined document. The app's route_schemer files must already be
    # loaded/required (Rails eager loading, or `rake route_schemer:swagger`, takes care of this).
    # @return [Hash] see {generate}
    def generate_from_loaded_classes
      classes = ObjectSpace.each_object(Class).select do |klass|
        name = klass.name.to_s
        name.end_with?("RouteSchemer") && name != "ApplicationRouteSchemer"
      end
      generate(classes)
    end

    # @return [Array<String>] the action names (e.g. "demo") that have a request or response
    #   schema defined on the given class
    def schema_actions(klass)
      klass.singleton_methods
           .grep(/_(?:request|response)_schema\z/)
           .map { |method| method.to_s.sub(/_(?:request|response)_schema\z/, "") }
           .uniq
    end

    # @return [Hash] the :request / :response schemas defined for a single action, omitting
    #   whichever side isn't defined
    def schemas_for(klass, action)
      {
        request: klass.respond_to?("#{action}_request_schema") ? klass.public_send("#{action}_request_schema") : nil,
        response: klass.respond_to?("#{action}_response_schema") ? klass.public_send("#{action}_response_schema") : nil
      }.compact
    end
  end
end
