name: Ruby

on:
  workflow_run:
      workflows:
        - Rubocop Auto Format
      types:
        - completed

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "3.0"
          - ruby: "3.1"
          - ruby: "3.2"
          - ruby: "3.3"
          - ruby: "3.3"
            rubyopt: "--enable-frozen-string-literal"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake ${{ matrix.rake_task }} RUBYOPT="${{ matrix.rubyopt }}"
        continue-on-error: true
      - name: Build gem
        run: gem build  --verbose *.gemspec
